<!-- formulario de alta de álbum -->
<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título del Álbum</label>
                <input required name="tituloAlbum" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>Artista del álbum</label>
                <select required name="artistaID" class="form-control">
                    <?php
                    foreach ($albumes as $album):
                        $artistaID = $album->artistaID;
                        $nombreArtista = $album->nombreArtista;
                    ?>
                        <option value="<?= $artistaID ?>"><?= $nombreArtista ?></option>
                    <?php
                    endforeach;
                    ?>
                </select>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label>Año de Lanzamiento</label>
        <textarea name="anioLanzamiento" class="form-control" rows="3"></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>
