<!-- formulario de alta de tarea -->
<form action="agregar" method="POST" class="my-4">
    <div class="row">
        <div class="col-9">
            <div class="form-group">
                <label>Título de la Cancion</label>
                <input required name="titulo" type="text" class="form-control">
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label>album al que pertenece</label>
                <select required name="albumID" class="form-control">
        <?php foreach ($canciones as $cancion): ?>
        <option value="<?= $cancion->albumID ?>"><?= $cancion->tituloAlbum ?></option>
        <?php endforeach ?>
</select>



            </div>
        </div>
    </div>

    <div class="form-group">    
        <label>Duracion de la cancion</label>
        <textarea name="Duración" class="form-control" rows="1"  ></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-2">Guardar</button>
</form>